from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
VERSION = "entity_complete_v2_coverage_expansion"
REPORT_DIR = REPO_ROOT / "algo_main" / "reports" / VERSION / "19_formal_algorithm_core_raw_to_batch"
DATA_DIR = REPO_ROOT / "algo_main" / "data" / VERSION / "13_formal_algorithm_core_raw_to_batch"
RAW_BATCH_DIR = DATA_DIR / "current_v2_raw_input_batch"
FORMAL_BATCH_DIR = DATA_DIR / "formal_result_batches" / "report_month=2025-12" / "batch_id=2025-12-monthly-risk-algorithm-formal-v2-raw"
FORMAL_CONFIG = REPO_ROOT / "configs" / "risk_algorithm_core" / "monthly_run.formal.example.yaml"
SCHEMA_MAPPING = REPO_ROOT / "configs" / "risk_algorithm_core" / "schema_mapping.example.yaml"


def read_report_csv(name: str) -> pd.DataFrame:
    path = REPORT_DIR / name
    if not path.exists():
        pytest.skip(f"{name} is generated by the formal raw-to-batch adapter")
    return pd.read_csv(path)


def require_raw_batch() -> Path:
    if not (RAW_BATCH_DIR / "manifest.json").exists():
        blocker = REPORT_DIR / "current_v2_raw_input_blocker.md"
        if blocker.exists():
            pytest.skip("current v2 raw input is blocked in this checkout")
        pytest.skip("current v2 raw input batch is generated from local ignored data")
    return RAW_BATCH_DIR


def require_formal_batch() -> Path:
    if not (FORMAL_BATCH_DIR / "manifest.json").exists():
        pytest.skip("formal result batch is generated from local ignored data")
    return FORMAL_BATCH_DIR
